import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='bg-right-bg-gradient bg-no-repeat bg-right-top'>
          <div className='bg-left-bg-gradient bg-no-repeat bg-[left_bottom_0.5rem]'>
          {children}
          </div>
        </div>
      </body>
    </html>
  )
}
